name: add comments on issues

on:
  issues:
    types: [opened]

jobs:
  commenter:
    runs-on: ubuntu-latest
    steps:
    - name: dump github context
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
